apiVersion : apps/v1
kind: Deployment
metadata:
  name: londonanthonyolearypipelinessampleapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: londonanthonyolearypipelinessampleapp
  template:
    metadata:
      labels:
        app: londonanthonyolearypipelinessampleapp 
    spec:
      containers:
        - name: londonanthonyolearypipelinessampleapp 
          image: demoresgistry.azurecr.io/londonanthonyolearypipelinessampleapp
          ports:
          - containerPort: 8080